# Generated by Django 4.2.3 on 2023-07-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_user_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
